// app/layout.tsx

import { TeacherLayout } from "@/components/layouts/teacherlayouts";
import { AuthProvider } from "@/context/AuthContext";
import "@/styles/globals.css";
import { Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast"; // <-- import Toaster

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <AuthProvider>
          <TeacherLayout>
            {/* Toaster added here */}
            <Toaster position="top-right" />
            {children}
          </TeacherLayout>
        </AuthProvider>
      </body>
    </html>
  );
}
